-- Broader trusted_sources for Indian news (fact checker tiers, LLD §11.2 step 5).
-- tier1: government and fact-check desks. tier2: established news organisations and wires.
-- Being listed is not an endorsement: a verdict needs the judge to rely on these sources, and
-- "high" confidence needs two independent publishers. Admins can edit this list.
-- (*.gov.in and *.nic.in are tier1 automatically in packages/fact-check/src/sources.ts.)

insert into public.trusted_sources (domain, tier, category) values
  -- Government and regulators outside *.gov.in
  ('rbi.org.in',                    'tier1', 'government'),
  ('mygov.in',                      'tier1', 'government'),
  ('sci.gov.in',                    'tier1', 'government'),
  ('who.int',                       'tier1', 'government'),
  ('un.org',                        'tier1', 'government'),
  -- Indian fact-check desks (IFCN signatories and established desks)
  ('newsmobile.in',                 'tier1', 'fact_checker'),
  ('factcrescendo.com',             'tier1', 'fact_checker'),
  ('newsmeter.in',                  'tier1', 'fact_checker'),
  ('thip.media',                    'tier1', 'fact_checker'),
  ('logicallyfacts.com',            'tier1', 'fact_checker'),
  ('youturn.in',                    'tier1', 'fact_checker'),
  ('digiteye.in',                   'tier1', 'fact_checker'),
  ('afp.com',                       'tier1', 'fact_checker'),
  -- News agencies
  ('ptinews.com',                   'tier2', 'news'),
  ('aninews.in',                    'tier2', 'news'),
  ('uniindia.com',                  'tier2', 'news'),
  ('ians.in',                       'tier2', 'news'),
  ('apnews.com',                    'tier2', 'news'),
  -- National English
  ('indiatoday.in',                 'tier2', 'news'),
  ('thequint.com',                  'tier2', 'news'),
  ('livemint.com',                  'tier2', 'news'),
  ('business-standard.com',         'tier2', 'news'),
  ('economictimes.indiatimes.com',  'tier2', 'news'),
  ('financialexpress.com',          'tier2', 'news'),
  ('moneycontrol.com',              'tier2', 'news'),
  ('newindianexpress.com',          'tier2', 'news'),
  ('deccanherald.com',              'tier2', 'news'),
  ('deccanchronicle.com',           'tier2', 'news'),
  ('tribuneindia.com',              'tier2', 'news'),
  ('telegraphindia.com',            'tier2', 'news'),
  ('thestatesman.com',              'tier2', 'news'),
  ('news18.com',                    'tier2', 'news'),
  ('firstpost.com',                 'tier2', 'news'),
  ('timesnownews.com',              'tier2', 'news'),
  ('republicworld.com',             'tier2', 'news'),
  ('wionews.com',                   'tier2', 'news'),
  ('scroll.in',                     'tier2', 'news'),
  ('theprint.in',                   'tier2', 'news'),
  ('outlookindia.com',              'tier2', 'news'),
  ('frontline.thehindu.com',        'tier2', 'news'),
  ('businesstoday.in',              'tier2', 'news'),
  ('livelaw.in',                    'tier2', 'news'),
  ('barandbench.com',               'tier2', 'news'),
  ('ddnews.gov.in',                 'tier1', 'government'),
  ('newsonair.gov.in',              'tier1', 'government'),
  -- Hindi and regional
  ('aajtak.in',                     'tier2', 'news'),
  ('ndtv.in',                       'tier2', 'news'),
  ('abplive.com',                   'tier2', 'news'),
  ('zeenews.india.com',             'tier2', 'news'),
  ('jagran.com',                    'tier2', 'news'),
  ('amarujala.com',                 'tier2', 'news'),
  ('bhaskar.com',                   'tier2', 'news'),
  ('livehindustan.com',             'tier2', 'news'),
  ('navbharattimes.indiatimes.com', 'tier2', 'news'),
  ('jansatta.com',                  'tier2', 'news'),
  ('patrika.com',                   'tier2', 'news'),
  ('lokmat.com',                    'tier2', 'news'),
  ('loksatta.com',                  'tier2', 'news'),
  ('mathrubhumi.com',               'tier2', 'news'),
  ('manoramaonline.com',            'tier2', 'news'),
  ('onmanorama.com',                'tier2', 'news'),
  ('eenadu.net',                    'tier2', 'news'),
  ('sakshi.com',                    'tier2', 'news'),
  ('dinamalar.com',                 'tier2', 'news'),
  ('dailythanthi.com',              'tier2', 'news'),
  ('anandabazar.com',               'tier2', 'news'),
  ('prajavani.net',                 'tier2', 'news'),
  ('divyabhaskar.co.in',            'tier2', 'news'),
  ('sandesh.com',                   'tier2', 'news'),
  -- International
  ('bbc.co.uk',                     'tier2', 'news'),
  ('aljazeera.com',                 'tier2', 'news'),
  ('theguardian.com',               'tier2', 'news'),
  ('nytimes.com',                   'tier2', 'news'),
  ('washingtonpost.com',            'tier2', 'news'),
  ('bloomberg.com',                 'tier2', 'news'),
  ('ft.com',                        'tier2', 'news'),
  ('cnn.com',                       'tier2', 'news'),
  ('cnbc.com',                      'tier2', 'news'),
  ('dw.com',                        'tier2', 'news'),
  ('france24.com',                  'tier2', 'news'),
  ('arabnews.com',                  'tier2', 'news'),
  ('gulfnews.com',                  'tier2', 'news'),
  ('khaleejtimes.com',              'tier2', 'news'),
  ('thenationalnews.com',           'tier2', 'news'),
  ('lemonde.fr',                    'tier2', 'news')
on conflict (domain) do nothing;

-- The seed's starter list, for databases that were created without seed.sql (hosted projects).
insert into public.trusted_sources (domain, tier, category) values
  ('pib.gov.in',                  'tier1', 'government'),
  ('factcheck.pib.gov.in',        'tier1', 'government'),
  ('india.gov.in',                'tier1', 'government'),
  ('uk.gov.in',                   'tier1', 'government'),
  ('boomlive.in',                 'tier1', 'fact_checker'),
  ('factly.in',                   'tier1', 'fact_checker'),
  ('vishvasnews.com',             'tier1', 'fact_checker'),
  ('altnews.in',                  'tier1', 'fact_checker'),
  ('newschecker.in',              'tier1', 'fact_checker'),
  ('thehindu.com',                'tier2', 'news'),
  ('indianexpress.com',           'tier2', 'news'),
  ('hindustantimes.com',          'tier2', 'news'),
  ('timesofindia.indiatimes.com', 'tier2', 'news'),
  ('ndtv.com',                    'tier2', 'news'),
  ('reuters.com',                 'tier2', 'news'),
  ('bbc.com',                     'tier2', 'news'),
  ('wikipedia.org',               'tier2', 'reference')
on conflict (domain) do nothing;
